name: blogapp-production

services:
  backend:
    environment:
      - PORT=3000
    # would probably want to remove this if actually deploying
    env_file:
      - ./backend/.env
    image: blogapp-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
  
  frontend:
    image: blogapp-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile

  proxy:
    image: nginx:1.27.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    
  